### ISSUE TITLE
C and CS examples compiled with Visual Studio 2015 won't run

### ISSUE THREAD

**Issue by nesdnuma** [sensel/sensel-api#4]
Hello,

I have installed the libraries and tried to compile the examples using Visual Studio 2015 (Community Edition) under Windows 10 Pro.

The compilation is successful but when I launch any .exe, a window seem to appear but disappears immediately, even before anything can be displayed and read.

What's wrong?

**Comment by AlexSensel** [comment]
Hello,

Thank you for reporting the issue. If you are running Hello Sensel, then the window could be closing because it completes or it can not find a device. If you are running another example like SenselContacts or SenselForces, then it is likely exiting because it cannot connect to the Sensel device. 

We will be adding key captures to each example that should prevent the console from closing before you can read all the data. After we add this and additional error checking, I will close this issue to let you know that the source has been updated.

In the meantime, you can add Sleep(5000) to the end of the c examples to see if any data is being printed. If the example can't find the Morph, make sure it is plugged in, the Sensel App is not open, and no other application are using the COM port.

**Comment by nesdnuma** [comment]
Hello,

Obviously there was indeed an issue with the COM port (it was probably still open in another application such as Arduino). Maybe some routine to test the ports would be useful. However the Sleep(5000) was mandatory to read the data too.

**Comment by AlexSensel** [comment]
It is great to hear that was the issue. We have added key inputs to each example to make sure the data remains on screen until you want to exit the program. As a result, I will be closing this issue. 

The easiest way to confirm that the Morph serial port is working is to open up the Sensel App and go into Morph Settings. There, it should read off the Serial Number and device firmware version. If it reads that data correctly, then the serial communication is working as expected. You can then exit the App and run the examples.
