### ISSUE TITLE
can't build 32-bit with pressure

### ISSUE THREAD

**Issue by batchku** [sensel/sensel-api#8]
Trying to build 32-bit sensel lib for raspberry pi 3 (`armv7l`)

I followed the readme instructions in the read me, so i did:

- I defined `#define SENSEL_PRESSURE 1` in `sensel.c`
- I ran `make`
- I got an error saying `sensel_decompress.h` can't be found
- i found that file inside the debian package, copied it to the `src` folder, ran make again, got this:
```
pi@MO:~/Development/sensel-api/sensel-lib $ make
rm -f src/*.o
gcc -c -std=c99 -Wall -Werror -fPIC -fvisibility=hidden -Isrc/ -DSENSEL_EXPORTS  -O2   -c -o src/sensel.o src/sensel.c
gcc -c -std=c99 -Wall -Werror -fPIC -fvisibility=hidden -Isrc/ -DSENSEL_EXPORTS  -O2   -c -o src/sensel_register.o src/sensel_register.c
gcc -c -std=c99 -Wall -Werror -fPIC -fvisibility=hidden -Isrc/ -DSENSEL_EXPORTS  -O2   -c -o src/sensel_serial_linux.o src/sensel_serial_linux.c
mkdir -p build/release/nopressure//obj
mv src/sensel.o src/sensel_register.o src/sensel_serial_linux.o build/release/nopressure//obj
gcc -shared -Wl,-soname,libsensel.so -o build/release/nopressure/libsensel.so build/release/nopressure//obj/sensel.o build/release/nopressure//obj/sensel_register.o build/release/nopressure//obj/sensel_serial_linux.o 
strip build/release/nopressure/libsensel.so
```
-here is the build folder that was created:
![image](https://user-images.githubusercontent.com/518356/30514058-45f62192-9adc-11e7-82bb-a27cfeb5addf.png)

-tried to execute `libsensel.so` on the pi, and got this error:
```
pi@MO:~/Development/sensel-api/sensel-lib/build/release/nopressure $ ./libsensel.so 
Segmentation fault
```

what now?

**Comment by AlexSensel** [comment]
I have added a 32 bit version of the .deb package for linux. This includes libsensel.so and libsenseldecompress.so that will be installed at /usr/lib. If you want to make changes to libsensel.so and you wish to use forces, then keep libsenseldecompress.so in /usr/lib and replace libsensel.so with your version of libsensel.so. Then you can compile and run the examples to confirm functionality. You cannot run a .so file. You should be able to compile libsensel.so with SENSEL_PRESSURE after you have installed libsenseldecompress.so.
